name: Run Tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Extract versions from .prototools
        id: versions
        run: |
          echo "pnpm=$(grep '^pnpm' ./.prototools | awk -F'\"' '{print $2}')" >> $GITHUB_OUTPUT
          echo "node=$(grep '^node' ./.prototools | awk -F'\"' '{print $2}')" >> $GITHUB_OUTPUT

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ steps.versions.outputs.pnpm }}
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ steps.versions.outputs.node }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test
